# SEO settings
title: "block"
title2: "LAB" # default: ""
description: "Das Netzwerk für Blockchain Technologie in der Region Stuttgart"
keywords: "Blockchain, Bitcoin, Ethereum, Stuttgart"
url: http://site.blocklab.de
baseurl: ""

google_analytics: UA-86796222-1
repo: http://github.com/blocklab/site

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "blockLAB"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
